"""add platform_token and platform_identity tables

Revision ID: e6f1ebb52cf3
Revises: dc1e3dfbb985
Create Date: 2026-06-16 20:26:32.836171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f1ebb52cf3'
down_revision: Union[str, Sequence[str], None] = 'dc1e3dfbb985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platformidentities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('platform',sa.String(), nullable=False),
    sa.Column('platform_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_id', name='uq_platform_identity')
    )
    op.alter_column('platformtokens', 'platform',
               existing_type=sa.VARCHAR(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platformtokens', 'platform',
               existing_type=sa.Enum('TELEGRAM', 'DISCORD', name='platforms'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('platformidentities')
    # ### end Alembic commands ###
